#!/bin/sh
#info: Build a custom Windows iso file with automatic Cygwin installation.
#info: Uses Wine, vmh and fastpkg. Run this inside Debian
# shellcheck disable=SC2039
# shellcheck disable=SC2129

### BASIC #####################################################################

set -e

# must run as normal user
if [ "$(id -u)" = 0 ]; then
    echo 'This script must be run as a normal user, not root!' >&2
    exit 1
fi

# parse arguments
if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    man isoremixer.1 || ronn -r <README.md | man -l -
    exit
else
    TARGET_OS="$1"
    ARGS="$2"
fi

### STATIC VARIABLES ##########################################################

# colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NOCOL=$(tput sgr0)

SP="_"
PATH_CFG="$HOME/.isoremixer"
PATH_PRESETS_USR="$PATH_CFG/presets"
PATH_PRESETS_SYS="/usr/local/share/isoremixer/presets"
FILE_TEMPLATE_USR="$PATH_PRESETS_USR/os/$TARGET_OS.ini"
FILE_TEMPLATE_SYS="$PATH_PRESETS_SYS/os/$TARGET_OS.ini"

### FUNCTIONS #################################################################

error() {
    if [ -n "$1" ]; then
        echo "${RED}Error, aborting:${NOCOL} $1" >&2
        echo "Check: $PATH_LOGS" >&2
    else
        echo "${RED}Error, aborting${NOCOL}" >&2
        echo "Check: $PATH_LOGS" >&2
    fi
    exit 1
}

info() {
    echo "${GREEN}### $1${NOCOL}"
}

info_edisk() {
    echo "${GREEN}### $1${NOCOL}"
    echo "### $1" >>"$LOG_EXTRA"
}

note() {
    echo "${RED}$1${NOCOL}"
}

require_app() {
    if [ -n "$(command -v "$1")" ]; then
        :
    elif ! [ -f "/usr/sbin/$1" ]; then
        error "$1 not found. Install to make this program work."
    fi
}

sudo_edisk() {
    # run as sudo but without writing to stdout
    local RESULT
    local FAILED

    echo "CMD:" "$@" >>"$LOG_EXTRA"
    RESULT=$(sudo "$@" 2>&1) || FAILED=true

    if [ -n "$FAILED" ]; then
        echo "$RESULT" >>"$LOG_EXTRA"
        echo "Error, aborting:" "$@"
        error "$RESULT"
    fi
}

get_fpkg_dl_path() {
    fastpkg -p "$1" show -d || error "fastpkg -p $1 show -d"
}

get_template() {
    local VAR=""
    VAR=$(grep -F "$1=" <"$FILE_TEMPLATE" | awk -F= '{print $2}' | tr -d '"')
    echo "$VAR"
    echo "$1: $VAR" >&2
}

extract_fpkg() {
    local PKG_NAME="$1"
    local OUT_FILE="$2"
    local PKG_PATH

    if [ -d "$OUT_FILE" ]; then
        info "skip, already extracted $PKG_NAME"
        return
    fi

    PKG_PATH=$(get_fpkg_dl_path "$PKG_NAME") || exit 1

    info "Extract $PKG_NAME"
    # extract and skip existing files
    7z -aos x "$PKG_PATH" -o"$OUT_FILE" 1>"$LOG_7Z" ||
        error "7z -aos x $PKG_PATH -o$OUT_FILE"
}

load_template() {
    info "Template is: $FILE_TEMPLATE"
    PROFILE=$(get_template PROFILE)
    WINE_WINVER=$(get_template WINE_WINVER)
    ARCH=$(get_template ARCH)
    PKG_CYGWIN=$(get_template PKG_CYGWIN)
    PKG_BUILDER=$(get_template PKG_BUILDER)
    PKG_ISO=$(get_template PKG_ISO)
    PKG_VIRTIO_ISO=$(get_template PKG_VIRTIO_ISO)
    PKG_SPICE_GT=$(get_template PKG_SPICE_GT)
    PKG_EXTRA_DRIVERS=$(get_template PKG_EXTRA_DRIVERS)
    PKG_CYGWIN_REPACK=$(get_template PKG_CYGWIN_REPACK)
    PKG_BUILD_IMAGE=$(get_template PKG_BUILD_IMAGE)
    CYGWIN_PKGS=$(get_template CYGWIN_PKGS)
    CYGWIN_URL=$(get_template CYGWIN_URL)
    CYGWIN_URL_PATH=$(get_template CYGWIN_URL_PATH)
}

assign_variables() {
    # find preset configs
    if [ -d "$PATH_PRESETS_USR/$PKG_BUILDER" ]; then
        PATH_PRESETS_SRC="$PATH_PRESETS_USR"
    elif [ -d "$PATH_PRESETS_SYS/$PKG_BUILDER" ]; then
        PATH_PRESETS_SRC="$PATH_PRESETS_SYS"
    else
        error "Missing preset folder for $PKG_BUILDER"
    fi
    info "Presets in: $PATH_PRESETS_SRC"

    # find deployment scripts
    PATH_PRESETS_ISO_SRC="$PATH_PRESETS_SRC/$PKG_BUILDER"
    NAME_SETUP_CYGWIN="setup_cygwin.bat"
    FILE_SETUP_CYGWIN="$PATH_PRESETS_SRC/$NAME_SETUP_CYGWIN"
    FILE_SETUP_SSHD="$PATH_PRESETS_SRC/setup_cygwin-sshd"
    CYGWIN_AUTO_NAME="cygwin-autoinstall"
    CYGWIN_NSIS_EXE="$CYGWIN_AUTO_NAME.exe"
    CYWGIN_NSIS_NSI="$CYGWIN_AUTO_NAME.nsi"
    FILE_CYWGIN_NSIS="$PATH_PRESETS_SRC/$CYWGIN_NSIS_NSI"
    CYGWIN_LINK="$CYGWIN_URL$CYGWIN_URL_PATH"
    PATH_ARCHIVE="$(echo "$CYGWIN_URL" | awk -F/ '{print $3}')"
    PREFIX_NAME="isoremixer$SP$ARCH$SP$PKG_ISO$SP$PKG_CYGWIN"
    PATH_PREFIX="$HOME/.local/share/wineprefixes/$PREFIX_NAME"
    PATH_C="$PATH_PREFIX/drive_c"
    PATH_CYGWIN="$PATH_C/cygwin-setup"
    PATH_ISO="$PATH_C/iso"
    PATH_DRIVERS="$PATH_C/drivers"
    PATH_PREPARE_ISO="$PATH_C/build-prepare"
    FILE_PREPARE_ISO="$PATH_PREPARE_ISO.iso"
    EXE_CYGWIN_SETUP="$PATH_CYGWIN/cygwin-setup.exe"

    FASTPKG_BASE="$PKG_CYGWIN $PKG_BUILDER"
    FASTPKG_DRIVERS="$PKG_EXTRA_DRIVERS $PKG_VIRTIO_ISO $PKG_SPICE_GT"
    FASTPKG_PKGS="$FASTPKG_BASE $FASTPKG_DRIVERS $PKG_ISO"

    VM_NAME="isoremixer-$PKG_BUILD_IMAGE"

    EXTRA_DISK_NAME="$PREFIX_NAME""-extra.raw"
    EXTRA_DISK_MNT="/media/$EXTRA_DISK_NAME"
    EXTRA_DISK="/var/lib/libvirt/images/$EXTRA_DISK_NAME"

    # nlite (via Wine)
    PATH_NLITE="$PATH_C/Program Files/nLite"
    EXE_NLITE="$PATH_NLITE/nLite.exe"
    PATH_PRESETS_DES="$PATH_NLITE/Presets"
    FILE_NLITE_PROFILE="$PATH_PRESETS_ISO_SRC/$PROFILE.ini"
    FILE_NLITE_PROFILE_U="$PATH_PRESETS_ISO_SRC/$PROFILE""_u.ini"

    # ntlite (via VM)
    PATH_NTLITE="$EXTRA_DISK_MNT/NTLite"
    PATH_NTLITE_PRESETS="$PATH_NTLITE/Presets"
    FILE_NTLITE_PROFILE="$PATH_PRESETS_ISO_SRC/$PROFILE.xml"
    FILE_NTLITE_CFG="$PATH_PRESETS_SRC/$PKG_BUILDER/settings.xml"

    # logs
    LOG_DATE=$(date +%Y%m%d_%H%M%S)
    PATH_LOGS="$PATH_CFG/logs/$PREFIX_NAME/$LOG_DATE"
    LOG_WINETRICKS="$PATH_LOGS/winetricks.log"
    LOG_7Z="$PATH_LOGS/7z.log"
    LOG_CYGWIN_DL="$PATH_LOGS/cygwin.log"
    LOG_NSIS="$PATH_LOGS/nsis.log"
    LOG_BUILDER_SETUP="$PATH_LOGS/builder_setup.log"
    LOG_BUILDER="$PATH_LOGS/builder.log"
    LOG_COPY="$PATH_LOGS/copy.log"
    LOG_EXTRA="$PATH_LOGS/extra_disk.log"
    LOG_GENISO="$PATH_LOGS/genisoimage.log"
    WINE_VER=$(wine --version | awk '{print $1}' | awk -F- '{print $2}')

    # use cygwin repack
    if echo "$ARGS" | grep -qF r; then
        FASTPKG_PKGS="$PKG_CYGWIN_REPACK $FASTPKG_PKGS"
    fi

    # set Wine architecture variables
    if [ "$ARCH" = "x86" ]; then
        ARCH_NR="32"
    elif [ "$ARCH" = "x64" ]; then
        ARCH_NR="64"
    else
        error "ARCH $ARCH not supported, only x86 and x64"
    fi

    # verify wine version
    if ! dpkg -l | grep -qL "wine$ARCH_NR"; then
        error "wine$ARCH_NR not installed"
    fi
}

download_cygwin_packages() {
    # start cygwin without quit mode, for debugging
    if echo "$ARGS" | grep -qF c; then
        if ! [ -d "$PATH_PREFIX" ]; then
            error "wineprefix not found, run without 'c' first"
        fi
        # debug
        cd "$PATH_CYGWIN" || error "cd $PATH_CYGWIN"

        # bug:
        # '--allow-unsupported-windows' does not work with: cygwin-32bit_2.874
        wine "$EXE_CYGWIN_SETUP" \
            --download \
            --arch="$ARCH" \
            --site="$CYGWIN_LINK" \
            --no-verify \
            --only-site \
            --local-package-dir="C:\cygwin-setup" \
            --packages="$CYGWIN_PKGS" 1>>"$LOG_CYGWIN_DL" 2>&1 ||
            error "check $LOG_CYGWIN_DL"
        exit 0

    elif [ -d "$PATH_CYGWIN" ]; then
        info "Cygwin already downloaded"
        remove_file "$LOG_COPY"

    else
        # download cygwin packages
        if ! echo "$ARGS" | grep -qF r; then
            info "Verify Wine version"
            case $WINE_VER in
            10.* | 9.* | 8.* | 7.* | 6.*)
                :
                ;;
            5.* | 4.* | 3.* | 2.* | 1.*)
                if ! [ "$TARGET_OS" = "xp" ]; then
                    echo "Wine is too old for this version of Cygwin-setup"
                    echo "You can only build XP images with Wine $WINE_VER"
                    echo "Use a repack instead by adding the 'r' flag"
                    error "Wine is too old"
                fi
                ;;
            *)
                error "wine '$WINE_VER' is not supported, update this script"
                ;;
            esac
        fi

        info "Create Wine prefix for '$WINE_WINVER'"
        winetricks settings "$WINE_WINVER" 1>/dev/null 2>&1 ||
            error winetricks

        # use repack
        if echo "$ARGS" | grep -qF r; then
            info "Using Cygwin repack"
            extract_fpkg "$PKG_CYGWIN_REPACK" "$PATH_CYGWIN"
        else
            make_dir_recursive "$PATH_CYGWIN"
        fi

        info "Copy cygwin setup exe"
        FILE_CYWGIN_SRC=$(get_fpkg_dl_path "$PKG_CYGWIN") || exit 1
        cp -Lv "$FILE_CYWGIN_SRC" "$EXE_CYGWIN_SETUP" >"$LOG_COPY" ||
            error "cp $FILE_CYWGIN_SRC"
        cd "$PATH_CYGWIN" || error "cd $PATH_CYGWIN"

        if ! echo "$ARGS" | grep -qF r; then
            info "Download Cygwin packages"
            wine "$EXE_CYGWIN_SETUP" \
                --quiet-mode \
                --download \
                --arch="$ARCH" \
                --site="$CYGWIN_LINK" \
                --no-verify \
                --only-site \
                --local-package-dir="C:\cygwin-setup" \
                --packages="$CYGWIN_PKGS" 1>>"$LOG_CYGWIN_DL" 2>&1 ||
                error "check $LOG_CYGWIN_DL"
        fi

    fi
}

send_key() {
    # shellcheck disable=SC2086
    virsh -q send-key "$VM_NAME" $1 $2 $3 $4 $5 $6 $7 $8 $9 1>/dev/null ||
        error "virsh send-key"
    sleep 1
}

force_unmount() {
    local MOUNT="$1"
    local DISK="$2"
    local MOUNTPOINT
    [ -n "$DISK" ] || error "missing DISK"
    [ -n "$MOUNT" ] || error "missing MOUNT"

    if sudo losetup -a | grep -qF "$DISK"; then
        info "Force unmount $DISK"
        sudo umount "$MOUNT" || true
        # detach loop device
        MOUNTPOINT=$(sudo losetup -a | grep -F "$DISK" | awk '{print $1}' |
            sed 's/://' | head -n1)
        echo "Detaching $MOUNTPOINT"
        if [ -n "$MOUNTPOINT" ]; then
            sudo losetup -d "$MOUNTPOINT" || true
        fi
    fi
}

remove_file() {
    if [ -f "$1" ]; then
        rm -vf "$1" >>"$LOG_COPY" || error "remove file $1"
    fi
}

remove_file_sudo() {
    if [ -f "$1" ]; then
        echo "remove file $1" >>"$LOG_COPY"
        sudo rm -f "$1" || error "remove file $1"
    fi
}

copy_file() {
    if [ -f "$2" ]; then
        info "skip, already copied $2"
        return 0
    fi
    [ -f "$1" ] || error "missing source file $1"
    [ -d "$(dirname "$2")" ] || error "missing folders for $2"
    cp -Lv "$1" "$2" >>"$LOG_COPY" || error "copy_file"
}

copy_recursive() {
    [ -d "$1" ] || error "missing source folder $1"
    [ -d "$(dirname "$2")" ] || error "missing folders for $2"
    cp -LvR "$1" "$2" >>"$LOG_COPY" || error "copy_recursive"
}

copy_cygwin() {
    local TARGET_DIR="$1"

    if [ -d "$TARGET_DIR" ]; then
        info "skip, already copied deployment scripts and Cygwin"
        return 0
    else
        make_dir_recursive "$TARGET_DIR"
    fi

    info "Copy deployment scripts"
    # and replace the word [PACKAGES] with the list of packages
    sed "s/\[PACKAGES\]/$CYGWIN_PKGS/g" "$FILE_SETUP_CYGWIN" \
        >"$TARGET_DIR/$NAME_SETUP_CYGWIN"
    copy_file "$FILE_SETUP_SSHD" "$TARGET_DIR/"

    info "Copy Cygwin exe"
    copy_file "$EXE_CYGWIN_SETUP" "$TARGET_DIR/"

    info "Copy Cygwin packages to ISO"
    CYGWIN_REPO=$(find -L "$PATH_CYGWIN" -mindepth 1 -maxdepth 1 \
        -name "*$PATH_ARCHIVE*" -type d) || error "find CYGWIN_REPO"
    [ -n "$CYGWIN_REPO" ] || error "CYGWIN_REPO not found"
    LIST_CYGWIN_REPO=$(find -L "$CYGWIN_REPO" -mindepth 1 -maxdepth 1 \
        -type d) || error "find LIST_CYGWIN_REPO"
    [ -n "$LIST_CYGWIN_REPO" ] || error "LIST_CYGWIN_REPO not found"
    for k in $LIST_CYGWIN_REPO; do
        copy_recursive "$k" "$TARGET_DIR/"
    done
}

make_dir_recursive() {
    if [ -d "$1" ]; then
        info "skip mkdir, directory already exists $1"
        return 0
    fi
    echo "create directory $1" >>"$LOG_COPY"
    mkdir -p "$1" || error "mkdir $1"
}

create_isoremixer_log() {
    if echo "$ARGS" | grep -qF r; then
        printf %s"\r\n" "USING_CYGWIN_REPACK: yes"
    else
        printf %s"\r\n" "USING_CYGWIN_REPACK: no"
    fi
    printf %s"\r\n" "LOG_DATE: $LOG_DATE" \
        "PREFIX_NAME: $PREFIX_NAME" \
        "CYGWIN_LINK: $CYGWIN_LINK" \
        "CYGWIN_PKGS: $CYGWIN_PKGS"
    for k in $FASTPKG_PKGS; do
        DL_PATH=$(get_fpkg_dl_path "$k")
        DL_PATH_BASE=$(basename "$DL_PATH")
        printf %s"\r\n" "FASTPKG_PKG: $DL_PATH_BASE"
    done
}

compile_cygwin_installer_cab() {
    info "Compile Cygwin installer to Hotfix CAB"
    local DIR_CAB="$PATH_C/cygwin-cab"
    local FOLDER_SVC="svcpack"
    local DIR_SVC="$DIR_CAB/$FOLDER_SVC"
    local FILE_INI="ENTRIES_Cygwin.INI"
    local PATH_CAB_INI="$DIR_CAB/$FILE_INI"

    mkdir -p "$DIR_SVC"
    ln -fs "$PATH_C/$CYGWIN_NSIS_EXE" "$DIR_SVC/$CYGWIN_NSIS_EXE"
    printf %s"\r\n" \
        "[general]" \
        "builddate=$(date +'%m/%d/%Y')" \
        "description=Cygwin" \
        "language=English" \
        "version=1.0" \
        "website=https://cygwin.com/" \
        "" \
        "[EditFile]" \
        "I386\SVCPACK.INF,SetupHotfixesToRun,AddProgram" \
        "" \
        "[AddProgram]" \
        "$CYGWIN_NSIS_EXE" \
        >"$PATH_CAB_INI"
    cd "$DIR_CAB" || error "cd $DIR_CAB"
    gcab -c "../$CYGWIN_AUTO_NAME.cab" "$FOLDER_SVC" "$FILE_INI"
}

compile_cygwin_installer_nsis() {
    info "Compile Cygwin installer with NSIS"
    copy_cygwin "$PATH_C/cygwin"
    copy_file "$FILE_CYWGIN_NSIS" "$PATH_C"
    cd "$PATH_C" || error "cd $PATH_C"
    makensis "$CYWGIN_NSIS_NSI" >"$LOG_NSIS" 2>&1 ||
        error "compile cygwin installer exe"
}

build_with_nlite() {
    require_app gcab

    # verify profile files
    [ -f "$FILE_NLITE_PROFILE" ] || error "missing $FILE_NLITE_PROFILE"
    [ -f "$FILE_NLITE_PROFILE_U" ] || error "missing $FILE_NLITE_PROFILE_U"

    if [ -d "$PATH_ISO" ]; then
        info "iso folder already created"
    else
        case $WINE_VER in
        10.* | 9.* | 8.0 | 7.* | 6.* | 5.* | 4.*)
            info "Install .NET 2.0 SP2 for nLite"
            winetricks -q dotnet20sp2 1>"$LOG_WINETRICKS" 2>&1 ||
                error "winetricks dotnet20sp2"
            # nlite requires tahoma font
            info "Install tahoma font for nLite"
            winetricks -q tahoma 1>"$LOG_WINETRICKS" 2>&1 ||
                error "winetricks tahoma"
            ;;
        *)
            error "wine version '$WINE_VER' not supported, update this script"
            ;;
        esac

        info "Install $PKG_BUILDER"
        wine "$EXE_BUILDER_SETUP" "/VERYSILENT" 1>"$LOG_BUILDER_SETUP" 2>&1 ||
            error "wine $EXE_BUILDER_SETUP"

        # extract and skip existing files
        extract_fpkg "$PKG_ISO" "$PATH_ISO"
        extract_fpkg "$PKG_VIRTIO_ISO" "$PATH_DRIVERS"
        # iterate over $PKG_EXTRA_DRIVERS
        for k in $PKG_EXTRA_DRIVERS; do
            extract_fpkg "$k" "$PATH_DRIVERS/$k"
        done
    fi

    info "Generate builder config"
    make_dir_recursive "$PATH_PRESETS_DES"
    FILE_NLITE_CFG_DES="$PATH_NLITE/nlite.ini"
    echo "[General]" >"$FILE_NLITE_CFG_DES"
    echo "NoCompatPop" >>"$FILE_NLITE_CFG_DES"
    echo "Path1 = C:\iso" >>"$FILE_NLITE_CFG_DES"

    info "Copy preset configs"
    copy_file "$FILE_NLITE_PROFILE" "$PATH_PRESETS_DES/"
    copy_file "$FILE_NLITE_PROFILE_U" "$PATH_PRESETS_DES/"

    compile_cygwin_installer_nsis
    compile_cygwin_installer_cab

    create_isoremixer_log >"$PATH_ISO/isoremixer.txt"

    info "Start $PKG_BUILDER"
    wine "$EXE_NLITE" 1>"$LOG_BUILDER" 2>&1 || error "wine $EXE_NLITE"
}

build_with_ntlite() {
    require_app genisoimage
    require_app vmh
    require_app parted
    require_app mkntfs
    require_app losetup
    require_app mount-image

    # verify profile files
    [ -f "$FILE_NTLITE_PROFILE" ] || error "missing $FILE_NTLITE_PROFILE"
    [ -f "$FILE_NTLITE_CFG" ] || error "missing $FILE_NTLITE_CFG"

    # using local libvirt
    if [ -z "$LIBVIRT_DEFAULT_URI" ]; then
        export LIBVIRT_DEFAULT_URI="qemu:///system"
    fi

    extract_fpkg "$PKG_VIRTIO_ISO" "$PATH_DRIVERS"

    if [ -d "$PATH_PREPARE_ISO" ]; then
        info "skip, already created Builder Prepare ISO"
    else
        info "Create Builder Prepare ISO"
        make_dir_recursive "$PATH_PREPARE_ISO"

        # copy builder tools
        copy_file "$EXE_BUILDER_SETUP" "$PATH_PREPARE_ISO/"
        copy_file "$EXE_SPICE_GT" "$PATH_PREPARE_ISO/"

        # copy guest additions (for builder OS)
        EXE_VIRTIO=$(find -L "$PATH_DRIVERS" -mindepth 1 -maxdepth 1 \
            -type f -name '*guest-tools*') || error "find EXE_VIRTIO"
        copy_file "$EXE_VIRTIO" "$PATH_PREPARE_ISO/"

        # create auto install script
        EXE_VIRTIO_BASE="$(basename "$EXE_VIRTIO")"
        VIRTIO_ARGS="/quiet /norestart /log %SYSTEMDRIVE%/$EXE_VIRTIO_BASE.log"
        # create, add extra disk, config file
        printf %s"\r\n" \
            "san policy=OnlineAll" \
            "select disk 1" \
            "online disk" \
            "attributes disk clear readonly" \
            >"$PATH_PREPARE_ISO/disks.txt" || error "add disks.txt"
        # create setup_builder.bat
        printf %s"\r\n" \
            "@echo off" \
            "rem echo Installing $EXE_VIRTIO_BASE" \
            "rem $EXE_VIRTIO_BASE $VIRTIO_ARGS" \
            "rem echo Check that $EXE_VIRTIO_BASE is installed" \
            "echo Installing $EXE_SPICE_GT_BIN" \
            "$EXE_SPICE_GT_BIN /S" \
            "echo Attach extra disk" \
            "diskpart /s disks.txt" \
            "echo Installing $EXE_BUILDER_SETUP_BIN" \
            "$EXE_BUILDER_SETUP_BIN /VERYSILENT /DIR=\"e:\NTLite\"" \
            "echo Press any key to reboot..." \
            "pause > nul" \
            "shutdown /r /t 0" \
            >"$PATH_PREPARE_ISO/setup_builder.bat" || error "add setup_builder"

        # create ISO
        remove_file "$FILE_PREPARE_ISO"
        genisoimage \
            -iso-level 4 \
            -o "$FILE_PREPARE_ISO" "$PATH_PREPARE_ISO" \
            1>"$LOG_GENISO" 2>&1 || error "genisoimage"
    fi
    [ -f "$FILE_PREPARE_ISO" ] || error "missing $FILE_PREPARE_ISO"

    # skip if already exists
    local VM_FIRST_RUN
    if sudo virsh list --all | grep -qF "$VM_NAME"; then
        info "skip, build VM already installed"
        # VM must be shutdown
        OFFLINE_VMS=$(sudo virsh list --all --state-shutoff --name)
        if ! echo "$OFFLINE_VMS" | grep -qxF "$VM_NAME"; then
            error "Build VM is not shut off"
        fi
        VM_FIRST_RUN=false
    else
        info "Install build VM"
        sudo vmh import "$VM_NAME" "$PKG_BUILD_IMAGE"
        VM_FIRST_RUN=true
    fi

    # create and attach extra disk
    if [ -f "$EXTRA_DISK" ]; then
        info "skip, extra disk already created"
        info "Disk image is: $EXTRA_DISK"
    else
        info "Create extra disk"
        touch "$LOG_EXTRA"
        force_unmount "$EXTRA_DISK_MNT" "$EXTRA_DISK"
        sudo_edisk qemu-img create -f raw "$EXTRA_DISK" 30G
        info_edisk "Format extra disk"
        sudo_edisk parted "$EXTRA_DISK" mklabel gpt
        info_edisk "Mount and format extra disk locally"
        sudo_edisk losetup -f "$EXTRA_DISK"
        MOUNTED_DISK=$(sudo losetup -a | grep -F "$EXTRA_DISK" |
            awk '{print $1}' | sed 's/://' | head -n1)
        echo "Disk device is: $MOUNTED_DISK" >>"$LOG_EXTRA"
        [ -n "$MOUNTED_DISK" ] || error "losetup -a"
        info_edisk "Create GTP disk label"
        # GPT disk label (you may get asked for confirmation)
        sudo_edisk parted -s "$MOUNTED_DISK" --align optimal unit MiB \
            mklabel gpt
        info_edisk "Create a single NTFS partition"
        sudo_edisk parted -s "$MOUNTED_DISK" --align optimal unit MiB \
            mkpart primary ntfs 1 100%
        info_edisk "Show partition table"
        sudo_edisk parted "$MOUNTED_DISK" print
        info_edisk "Generate device nodes"
        sudo_edisk partprobe "$MOUNTED_DISK"
        info_edisk "Format first partition with NTFS"
        sudo_edisk mkntfs --fast --force "$MOUNTED_DISK"*1
        info_edisk "Unmount extra disk"
        sudo_edisk losetup -d "$MOUNTED_DISK"
    fi

    # copy everything to extra disk
    info_edisk "Mount extra disk locally"
    force_unmount "$EXTRA_DISK_MNT" "$EXTRA_DISK"
    sudo_edisk mount-image "$EXTRA_DISK" "$EXTRA_DISK_MNT"
    extract_fpkg "$PKG_ISO" "$EXTRA_DISK_MNT/iso"
    extract_fpkg "$PKG_VIRTIO_ISO" "$EXTRA_DISK_MNT/drivers"
    # iterate over $PKG_EXTRA_DRIVERS
    for k in $PKG_EXTRA_DRIVERS; do
        extract_fpkg "$k" "$EXTRA_DISK_MNT/drivers/$k"
    done
    info "Copy $PKG_BUILDER profile to extra disk"
    make_dir_recursive "$PATH_NTLITE_PRESETS"
    copy_file "$FILE_NTLITE_PROFILE" "$PATH_NTLITE_PRESETS/"
    info "Copy $PKG_BUILDER settings to extra disk"
    copy_file "$FILE_NTLITE_CFG" "$PATH_NTLITE/"

    compile_cygwin_installer_nsis
    info "Copy $CYGWIN_NSIS_EXE profile to extra disk"
    copy_file "$PATH_C/$CYGWIN_NSIS_EXE" "$EXTRA_DISK_MNT/"

    info "Copy drivers to extra disk ISO folder"
    cp -LR "$EXTRA_DISK_MNT/drivers" "$EXTRA_DISK_MNT/iso/drivers" ||
        error "copy extra disk drivers"
    sync
    create_isoremixer_log >"$EXTRA_DISK_MNT/iso/isoremixer.txt"
    info_edisk "Unmount extra disk locally"
    sudo_edisk umount-image "$EXTRA_DISK" "$EXTRA_DISK_MNT"

    info "Attach prepare ISO to sdb"
    sudo virsh -q change-media "$VM_NAME" sdb "$FILE_PREPARE_ISO" --update \
        1>/dev/null || error "virsh change-media"

    # attach extra disk to VM
    info "Detach extra disk on vdb"
    sudo virsh -q detach-disk "$VM_NAME" --current vdb 2>/dev/null || true
    info "Attach extra disk to vdb"
    sudo virsh -q attach-disk "$VM_NAME" "$EXTRA_DISK" --current vdb \
        --driver=qemu || error "virsh attach-disk vdb"

    # boot VM
    info "Start build VM"
    sudo vmh start "$VM_NAME" || error "vmh start"
    if [ "$VM_FIRST_RUN" = "true" ]; then
        WAIT_TIME=110
        MSG_BOOT="Please wait $WAIT_TIME seconds while the VM is booting."
        note "$MSG_BOOT"
        notify-send -t 10000 "$MSG_BOOT"
        sleep $WAIT_TIME
        if echo "$PKG_BUILD_IMAGE" | grep -qF "cloudbase"; then
            info "Looks like a Cloudbase image"
            # set a password
            info "Set admin password to '1qa!QA'"
            send_key KEY_ENTER
            send_key KEY_1 KEY_Q KEY_A KEY_LEFTSHIFT KEY_1 KEY_Q KEY_A
            send_key KEY_TAB
            send_key KEY_1 KEY_Q KEY_A KEY_LEFTSHIFT KEY_1 KEY_Q KEY_A
            send_key KEY_ENTER
            info "Wait for password to change"
            sleep 5
            send_key KEY_ENTER
            MSG_SETTINGS="Please wait 10 seconds while the VM is configuring."
            note "$MSG_SETTINGS"
            notify-send -t 10000 "$MSG_SETTINGS"
            sleep 10
            send_key KEY_LEFTALT KEY_F4
            send_key KEY_LEFTALT KEY_R
        fi
    fi

    # connect remote-viewer
    virt-viewer "$VM_NAME" --wait 1>/dev/null 2>&1 &
    # build iso
    echo "Prepare the VM by running setup_builder.bat from the CD drive."
    echo "Bug: You might need to run it twice after rebooting the VM."
    echo "This fixes a slow mouse cursor and/or graphical issues."
    echo "Then run $PKG_BUILDER in the VM and create your custom ISO."
    echo "When done, answer the following question:"
    echo ""

    # question on what to do when done
    DO_SHUTDOWN=false
    DO_MOUNT=false
    while true; do
        echo "Shutdown the build VM?"
        echo "  Enter 's' to shutdown the VM"
        echo "  Enter 'm' to shutdown the VM and mount disk (to copy out iso)"
        echo "  Enter 'k' to keep the current VM state and no mount (skip)"
        # shellcheck disable=SC2162
        read INSTMED </dev/tty
        case $INSTMED in
        s)
            DO_SHUTDOWN=true
            break
            ;;
        m)
            DO_SHUTDOWN=true
            DO_MOUNT=true
            break
            ;;
        k)
            break
            ;;
        esac
    done
    if [ "$DO_SHUTDOWN" = true ]; then
        info "Shutdown the build VM"
        sudo vmh shutdown "$VM_NAME" || error "vmh shutdown $VM_NAME"
    fi
    if [ "$DO_MOUNT" = true ]; then
        sudo mount-image "$EXTRA_DISK" || error "mount-image"
    else
        echo "Mount the extra disk with:"
        echo "  sudo mount-image \"$EXTRA_DISK\""
    fi
    echo "Unmount with:"
    echo "  sudo umount-image \"$EXTRA_DISK\""
    echo ""
    echo "As a final step, you might want to rename the ISO file."
    echo "For example add the release type:"
    echo "from windows-10-isoremixer-minimal.iso"
    echo "  to windows-10-pro-isoremixer-minimal.iso"
}

### INIT ######################################################################

# verify base requirements
require_app fastpkg
require_app wine
require_app winetricks
require_app 7z
require_app makensis

# load template
if [ -f "$FILE_TEMPLATE_USR" ]; then
    FILE_TEMPLATE="$FILE_TEMPLATE_USR"
elif [ -f "$FILE_TEMPLATE_SYS" ]; then
    FILE_TEMPLATE="$FILE_TEMPLATE_SYS"
else
    error "Missing template: $FILE_TEMPLATE_USR or $FILE_TEMPLATE_SYS"
fi
load_template || error

assign_variables

# create base folders
mkdir -p "$PATH_PRESETS_USR" || error "mkdir user presets"
mkdir -p "$PATH_LOGS" || error "mkdir logs"

### MAIN ######################################################################

echo "Requires superuser privileges:"
if ! sudo true "$USER"; then
    echo 'The user is unable to become root!' >&2
    exit 1
fi

# cleanup old build session
if echo "$ARGS" | grep -qF e; then
    if [ -n "$(command -v vmh)" ]; then
        info "Shutdown VM"
        sudo vmh shutdown "$VM_NAME" 2>/dev/null || true
        force_unmount "$EXTRA_DISK_MNT" "$EXTRA_DISK"
        info "Erase old build session extra disk"
        remove_file_sudo "$EXTRA_DISK"
    fi
    info "Erase old build session path"
    rm -fr "$PATH_PREFIX" || error "remove folder"
    exit 0
fi

# cleanup old build session extra disk
if echo "$ARGS" | grep -qF x; then
    if [ -n "$(command -v vmh)" ]; then
        info "Shutdown VM"
        sudo vmh shutdown "$VM_NAME" 2>/dev/null || true
        force_unmount "$EXTRA_DISK_MNT" "$EXTRA_DISK"
        info "Erase old build session extra disk"
        remove_file_sudo "$EXTRA_DISK"
    fi
    exit 0
fi

# purge everything
if echo "$ARGS" | grep -qF p; then
    if [ -n "$(command -v vmh)" ]; then
        info "Erase old build session VM"
        sudo vmh erase "$VM_NAME" 2>/dev/null || true
        force_unmount "$EXTRA_DISK_MNT" "$EXTRA_DISK"
        info "Erase old build session extra disk"
        remove_file_sudo "$EXTRA_DISK"
    fi
    info "Erase old build session path"
    rm -fr "$PATH_PREFIX" || error "remove folder"
    exit 0
fi

# download fastpkg packages
if ! echo "$ARGS" | grep -qF s; then
    info "Download fastpkg packages"
    sudo fastpkg -q update || error
    for i in $FASTPKG_PKGS; do
        sudo fastpkg -p "$i" download || error
    done
    # install build image
    if [ -n "$PKG_BUILD_IMAGE" ]; then
        sudo fastpkg -p "$PKG_BUILD_IMAGE" install || error
    fi
fi

# set wine prefix variables
info "Set wine prefix variables"
export WINEARCH="win$ARCH_NR"
info "WINEARCH=$WINEARCH"
export WINEPREFIX="$PATH_PREFIX"
info "WINEPREFIX=$WINEPREFIX"

# download cygwin packages
download_cygwin_packages || error "failed to download cygwin packages"

# only download cygwin packages
if echo "$ARGS" | grep -qF d; then
    echo "Cygwin packages downloaded to: $PATH_CYGWIN"
    exit
fi

# set more variables
EXE_BUILDER_SETUP=$(get_fpkg_dl_path "$PKG_BUILDER")
EXE_BUILDER_SETUP_BIN="$(basename "$EXE_BUILDER_SETUP")"
EXE_SPICE_GT=$(get_fpkg_dl_path "$PKG_SPICE_GT")
EXE_SPICE_GT_BIN="$(basename "$EXE_SPICE_GT")"

# build iso
case $PKG_BUILDER in
nlite*)
    build_with_nlite
    ;;
ntlite*)
    build_with_ntlite
    ;;
*)
    error "$PKG_BUILDER is not supported, must start with 'nlite' or 'ntlite'"
    ;;
esac
